hologramsEnabled: true
particlesEnabled: true
effectsEnabled: true

food:
  iron_carrot:
    type: multiple
    custom_id: 1
    name: '&cIron Carrot'
    custom_model_data: 1
    material: CARROT
    particle:
      on_place:
        name: CRIT_MAGIC
        amount: 12
      on_harvest:
        name: CRIT_MAGIC
        amount: 12
      on_eat:
        name: CRIT_MAGIC
        amount: 12
    effect:
      name:
    food_level: 20
    place:
      type: multiple
      allowedBlocks:
        - farmland
      material: CARROTS
      droppedItem:
          amount:
            - 1
            - 2