hologramsEnabled: true
blockBreak: true

food:
  iron_carrot:
    type: multiple
    custom_id: 1
    name: '&cIron Carrot'
    custom_model_data: 1
    material: CARROT
    food_level: 20
    place:
      type: multiple
      allowedBlocks:
        - farmland
      material: CARROTS
      droppedItem:
          amount:
            - 1
            - 2