hologramsEnabled: true

food:
  iron_apple:
    custom_id: 1
    name: '&cIron Carrot'
    custom_model_data: 1
    material: CARROT
    food_level: 20
    place:
      allowedBlocks:
        - farmland
      material: CARROTS
      droppedItems:
        Carrot:
          custom_id: 1
          amount:
            - 1
            - 2