name: AbstractionExamplePluginUpdated
main: org.kitteh.example.plugin.MyPlugin
author: __AltDemono__
description: testing
version: '1.0.0-SNAPSHOT'
api-version: '1.13'
commands:
  example:
    description: Example command
    usage: /example message here